version: '3.8'
networks:
  vpc:
    driver: bridge
services:
  admin-proxy:
    build: ./admin-proxy
    ports:
      - "8000:8000"
    networks:
      - vpc
    env_file:
      - ./admin-proxy/.env
    environment:
      - NODE_ENV=development
      - microservice1=http://microservice1:3000
  microservice1:
    build: ./testMicroservice
    networks:
      - vpc
    deploy: # Example of load balancing with service discovery using virtual ip address
      mode: replicated
      replicas: 2
      endpoint_mode: vip