version: '3.8'
networks:
  vpc:
    driver: bridge
services:
  # points:
  #   image: bryan/points
  #   build: .
  #   restart: always
  #   ports:
  #     - "3000:3000"
  redis:
    image: redis:alpine
    restart: always
    networks:
      - vpc
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
      - HTTP_USER=default
      - HTTP_PASSWORD=password
    ports:
      - 8081:8081
    networks:
      - vpc
    depends_on:
      - redis
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - vpc
    expose:
      - "8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app-node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app-node
    ports:
      - "3000:3000"
    networks:
      - vpc
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
  #   environment:
  #     AWS_ACCESS_KEY_ID: 'bryan'
  #     AWS_SECRET_ACCESS_KEY: 'lee'
  #     REGION: 'local'