name: Reusable Node Test Workflow

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Folder to test'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cd into the repo
        run: cd ./${{ github.event.inputs.folder }}
      - name: Set up node 16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test