name: Reusable Node Test Workflow

on:
  workflow_call:
    inputs:
      folder:
        default: '"admin-proxy'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      folder:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cd into the repo
        run: cd "/admin-proxy"
        shell: bash
      - name: Set up node 16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test