name: Run Frontend CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_FULL_ACCESS_SECRET}}
          aws-secret-access-key: ${{ secrets.AWS_S3_FULL_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Trigger Frontend Workflow
        working-directory: spm_frontend
        run: |
          npm install
          npm run build
          aws s3 sync ./dist/ s3://spm-frontend --delete
